services:

  postgres:
    env_file:
      - .env.dev.local
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD:-example}'
    ports:
      - '${DB_PORT:-5432}:5432'

  adminer:
    env_file:
      - .env.dev.local
    image: adminer
    restart: always
    ports:
      - '${ADMINER_PORT:-8080}:8080'
